// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx_p9sDsKP_cNxMyBJtNfmnHNCi5oDDG8',
    appId: '1:150962081809:android:85c91ada55d754dbd7a1b0',
    messagingSenderId: '150962081809',
    projectId: 'gem-dubai-4bd71',
    storageBucket: 'gem-dubai-4bd71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMbEVSb71dx9InPBhF9KjahY9n2jvYZF4',
    appId: '1:150962081809:ios:9c6de776e1b161ced7a1b0',
    messagingSenderId: '150962081809',
    projectId: 'gem-dubai-4bd71',
    storageBucket: 'gem-dubai-4bd71.appspot.com',
    androidClientId: '150962081809-sbvcu2hv329bs3684hcji1e6338vidu0.apps.googleusercontent.com',
    iosClientId: '150962081809-1pg3ufrtme970sk2lg83p4nhl2e9uaqo.apps.googleusercontent.com',
    iosBundleId: 'com.gem.testmobile',
  );
}
